204 every new account gets a randomized username
citizenwallet/app pull request #206
Opened 2024-11-12 03:59 UTC by SajeeTechi

Closes #204

2024-11-13 09:17 UTC, kevtechi requested changes
Feedback given during a call.

For migration of contacts:
1. there should be a json profile in the table
2. take data from there or don't migrate the row

For fetching a profile:
1. get from db
3. if not available locally >> await fetch from profile contract (add to db)
4. if available locally >> return immediately (async update from profile contract)

2024-11-19 09:33 UTC, kevtechi requested changes

2024-11-19 09:33 UTC, kevtechi commented on lib/services/db/backup/accounts.dart
> +    Future<void> _migrateProfiles(Database db) async {
this migration is not needed. Every time an account is opened, we go to the wallet screen and go through the profile async loading flow which will load or create one

2024-11-19 09:33 UTC, kevtechi commented on lib/services/db/backup/accounts.dart
> +        'ALTER TABLE $name ADD COLUMN username TEXT DEFAULT NULL',
you only need the table column migration

2024-11-19 09:33 UTC, kevtechi commented on lib/state/profile/logic.dart
>          profile,
upsert as well from the db fetch

2024-11-19 11:15 UTC, SajeeTechi commented on lib/state/profile/logic.dart
> +        DBAccount(
i am updating the values `name`, `username` and `profile`

`alias` and `address` are required to create the unique identifier for the update query

2024-11-20 08:09 UTC, kevtechi approved these changes

2024-11-20 08:09 UTC, merged